# Generated by Django 6.0.3 on 2026-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("qlab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_label", models.CharField(max_length=500, unique=True)),
                ("app_label", models.CharField(max_length=250)),
                ("model_name", models.CharField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("submitted", "Submitted"),
                        ],
                        default="submitted",
                        max_length=16,
                    ),
                ),
                ("is_restricted", models.BooleanField(default=False)),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True, related_name="registered_models", to="auth.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Registry",
                "verbose_name_plural": "Model Registry",
                "ordering": ["-created_at"],
            },
        ),
    ]
